import { fileURLToPath } from "url";
import fs from "fs";
import path from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MAKI_DIR = path.join(__dirname, "../node_modules/@mapbox/maki/icons");
const TEMAKI_DIR = path.join(__dirname, "../node_modules/@rapideditor/temaki/icons");
const OUTPUT_CSS = path.join(__dirname, "../css/icons.css");

// Mapping: internal_name -> source_name (or array of candidates)
// If source_name is null, use internal_name
const ICONS = {
  "alcohol": "alcohol-shop",
  "bakery": "bakery",
  "bar": "bar",
  "bbq": "bbq",
  "beauty": ["beauty_salon", "beauty"],
  "bicycle": "bicycle",
  "butcher": ["cleaver", "meat", "butcher"],
  "cafe": "cafe",
  "cinema": "cinema",
  "clothes": ["clothing-store", "clothes"],
  "college": "college",
  "confectionery": "confectionery",
  "convenience": "convenience",
  "department_store": ["shopping_mall", "department_store"],
  "diy": ["tools", "diy"],
  "fast_food": "fast-food",
  "fuel": "fuel",
  "garden_centre": "garden-centre",
  "gift": "gift",
  "golf": "golf",
  "greengrocer": ["grapes", "food", "grocery"],
  "guest_house": "lodging",
  "hairdresser": "hairdresser",
  "hospital": "hospital",
  "hut": "hut",
  "ice_cream": "ice-cream",
  "library": "library",
  "memorial": ["monument", "memorial"],
  "museum": "museum",
  "music": "music",
  "pharmacy": "pharmacy",
  "pitch": "pitch",
  "place_of_worship": "place-of-worship",
  "playground": "playground",
  "pub": ["beer", "pub"],
  "restaurant": "restaurant",
  "restaurant-pizza": "restaurant-pizza",
  "school": "school",
  "shelter": "shelter",
  "shoe": "shoe",
  "shop": "shop",
  "spa": "spa",
  "sports": ["stadium", "soccer", "sports"],
  "stadium": "stadium",
  "star-stroked": "star-stroked",
  "supermarket": ["grocery", "supermarket"],
  "swimming": "swimming",
  "theatre": "theatre"
};

function findIcon(name) {
  const candidates = Array.isArray(name) ? name : [name];

  for (const candidate of candidates) {
    // Try Maki (hyphens)
    const makiPath = path.join(MAKI_DIR, `${candidate}.svg`);
    if (fs.existsSync(makiPath)) { return makiPath; }

    // Try Temaki (underscores)
    const temakiName = candidate.replace(/-/gu, "_");
    let temakiPath = path.join(TEMAKI_DIR, `${temakiName}.svg`);
    if (fs.existsSync(temakiPath)) { return temakiPath; }

    // Try Temaki (original)
    temakiPath = path.join(TEMAKI_DIR, `${candidate}.svg`);
    if (fs.existsSync(temakiPath)) { return temakiPath; }
  }
  return null;
}

function generateCSS() {
  let css = `/* Generated by scripts/generate_icons.js */
.marker::after {
    content: '';
    display: block;
    width: 100%;
    height: 100%;
    background-color: currentColor;
    mask-repeat: no-repeat;
    mask-position: center;
    mask-size: contain;
}
`;

  for (const [internalName, sourceName] of Object.entries(ICONS)) {
    const iconPath = findIcon(sourceName || internalName);

    if (iconPath) {
      const svgContent = fs.readFileSync(iconPath, "utf8");
      // Simple optimization: remove newlines and double spaces
      const optimizedSvg = svgContent
        .replace(/\n/gu, "")
        .replace(/\s+/gu, " ")
        .replace(/>\s+</gu, "><")
        .replace(/"/gu, "'");

      const dataUri = `data:image/svg+xml,${encodeURIComponent(optimizedSvg)}`;

      css += `
.icon-${internalName}::after {
    mask-image: url("${dataUri}");
}
`;
    }
    else {
      console.warn(`Warning: Icon not found for '${internalName}' (source: ${sourceName})`);
    }
  }

  fs.writeFileSync(OUTPUT_CSS, css);
  console.log(`Generated ${OUTPUT_CSS}`);
}

generateCSS();
